-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 16:03:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gamificacao` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamificacao` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `gamificacao` ;

-- -----------------------------------------------------
-- Table `alternativa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alternativa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `alternativa` (
  `idalternativa` INT NOT NULL auto_increment,
  `pergunta_idpergunta` INT NOT NULL,
  `texto` VARCHAR(100) NULL,
  `correta` BOOLEAN,
  PRIMARY KEY (`idalternativa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `atividade` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `atividade` (
  `idatividade` INT NOT NULL auto_increment,
  `valor` INT NULL,
  `postagem_idpostagem` INT NOT NULL,
  `dataentrega` DATE NULL,
  PRIMARY KEY (`idatividade`),
  CONSTRAINT `fk_atividade_postagem1`
    FOREIGN KEY (`postagem_idpostagem`)
    REFERENCES `postagem` (`idpostagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `avaliacao` (
  `nota` INT NULL,
  `avaliador` INT NOT NULL,
  `avaliado` INT NOT NULL,
  PRIMARY KEY (`avaliador`, `avaliado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chat` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `chat` (
  `idchat` INT NOT NULL,
  PRIMARY KEY (`idchat`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `chat_has_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chat_has_usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `chat_has_usuario` (
  `chat_idchat` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`chat_idchat`, `usuario_idusuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comentario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `comentario` (
  `idcomentario` INT NOT NULL auto_increment,
  `postagem_idpostagem` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `comentario` VARCHAR(240) NULL,
  PRIMARY KEY (`idcomentario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `formulario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formulario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `formulario` (
  `idformulario` INT NOT NULL auto_increment,
  `usuario_idusuario` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `descricao` VARCHAR(150) NULL,
  PRIMARY KEY (`idformulario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `isignia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `isignia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `isignia` (
  `idisignia` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `tipoisi_idtipoisi` INT NOT NULL,
  `icone` BLOB NULL,
  PRIMARY KEY (`idisignia`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mensagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mensagem` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mensagem` (
  `idmensagem` INT NOT NULL,
  `chat_idchat` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `mensagem` VARCHAR(5000) NULL,
  PRIMARY KEY (`idmensagem`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pergunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pergunta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pergunta` (
  `idpergunta` INT NOT NULL auto_increment,
  `formulario_idformulario` INT NOT NULL,
  `questao` VARCHAR(250) NULL,
  `tipoper_idtipoper` INT NOT NULL,
  PRIMARY KEY (`idpergunta`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ponto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponto` (
  `idponto` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `quantidade` INT NULL,
  `sala_idsala` INT NOT NULL,
  PRIMARY KEY (`idponto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `postagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `postagem` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `postagem` (
  `idpostagem` INT NOT NULL auto_increment,
  `usuario_idusuario` INT NOT NULL,
  `texto` varchar(280),
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`idpostagem`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `postagem_has_atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `postagem_has_atividade` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `postagem_has_atividade` (
  `postagem_idpostagem` INT NOT NULL,
  `atividade_idatividade` INT NOT NULL,
  PRIMARY KEY (`postagem_idpostagem`, `atividade_idatividade`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sala` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sala` (
  `idsala` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NULL,
   `descricao` VARCHAR(45) NULL,
    `cor` VARCHAR(6) NULL,
  PRIMARY KEY (`idsala`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sala_has_postagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sala_has_postagem` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sala_has_postagem` (
  `sala_idsala` INT NOT NULL,
  `postagem_idpostagem` INT NOT NULL,
  PRIMARY KEY (`sala_idsala`, `postagem_idpostagem`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sala_has_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sala_has_usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sala_has_usuario` (
  `sala_idsala` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `tipousu_idtipousu` INT NOT NULL,
  PRIMARY KEY (`sala_idsala`, `usuario_idusuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tipoisi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipoisi` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipoisi` (
  `idtipoisi` INT NOT NULL auto_increment,
  `caminhoimg` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipoisi`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tipoper`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipoper` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipoper` (
  `idtipoper` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipoper`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tipousu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipousu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipousu` (
  `idtipousu` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipousu`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL auto_increment,
  `nome` VARCHAR(100) NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `dtNasc` DATE NULL,
  `email` VARCHAR(150) NULL,
  `senha` VARCHAR(100) NULL,
  `cor` VARCHAR(7) NULL,
  `imguser` VARCHAR(100) NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) ,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) )
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuario_responde_formulario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario_responde_formulario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario_responde_formulario` (
  `usuario_idusuario` INT NOT NULL,
  `formulario_idformulario` INT NOT NULL,
  `pontuacao`INT,
  `dataenvio`date,
  PRIMARY KEY (`usuario_idusuario`, `formulario_idformulario`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;